### Section 0: Data Loading
We are loading the Titanic dataset using the Seaborn library as an alternative to Kaggle to avoid authentication requirements.

In [15]:
import pandas as pd
import seaborn as sns

# Load the dataset from Seaborn
df = sns.load_dataset('titanic')
df_original = df.copy()

print(f"Dataset successfully loaded. Initial Shape: {df.shape}")
display(df.head())

Dataset successfully loaded. Initial Shape: (891, 15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Section 1: Data Loading and Initial Quality Report
In this section, we load the raw Titanic dataset directly from the Seaborn library and perform an initial inspection for missing values and duplicates to establish a baseline for cleaning.

In [16]:
import pandas as pd
import numpy as np
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')
df_original = df.copy()

print(f"Initial Data Shape: {df.shape}")
print("\nMissing Values Per Column:")
print(df.isnull().sum())
print(f"\nInitial Duplicate Rows Count: {df.duplicated().sum()}")

Initial Data Shape: (891, 15)

Missing Values Per Column:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Initial Duplicate Rows Count: 107

### Section 2: Missing Data Handling
We address missingness by imputing the median for 'age' (to handle skewness), the mode for categorical columns like 'embarked', and dropping the 'deck' column which lacks sufficient data for reliable analysis.

In [17]:
# Handle missing values
df['age'] = df['age'].fillna(df['age'].median())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
df = df.drop(columns=['deck'])

print("Missing values resolved: 'age' imputed with median, 'embarked' with mode, and 'deck' column dropped.")

Missing values resolved: 'age' imputed with median, 'embarked' with mode, and 'deck' column dropped.

### Section 3: Duplicate Removal
To ensure statistical integrity and avoid bias, we identify and remove exact duplicate rows from the dataset.

In [18]:
# Remove duplicates
before_dedup = len(df)
df = df.drop_duplicates()
after_dedup = len(df)

print(f"Dropped {before_dedup - after_dedup} duplicate rows.")

Dropped 116 duplicate rows.

### Section 4: Outlier Detection and Capping (IQR Method)
We use the Interquartile Range (IQR) method to identify extreme values in the 'fare' column and cap them at the upper statistical boundary to prevent skewed results.

In [19]:
# IQR Outlier capping
Q1 = df['fare'].quantile(0.25)
Q3 = df['fare'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

outliers_count = len(df[df['fare'] > upper_bound])
df['fare'] = np.where(df['fare'] > upper_bound, upper_bound, df['fare'])

print(f"Detected {outliers_count} outliers in 'fare'. Capped at: {round(upper_bound, 2)}")

Detected 102 outliers in 'fare'. Capped at: 73.42

### Section 5: Data Quality Comparison and Export
This final section provides a comparison table showing the dataset status before and after cleaning, and exports the final result to a CSV file.

In [20]:
# Summary Table
summary_data = {
    'Metric Status': ['Total Row Count', 'Total Missing Values', 'Total Duplicate Rows', 'Deck Column Status', 'Fare Outliers Capped'],
    'BEFORE Cleaning': [df_original.shape[0], df_original.isnull().sum().sum(), df_original.duplicated().sum(), 'Present', 'No'],
    'AFTER Cleaning': [df.shape[0], df.isnull().sum().sum(), df.duplicated().sum(), 'Dropped', f'Yes ({outliers_count})']
}

summary_table = pd.DataFrame(summary_data)
display(summary_table)

# Export
df.to_csv('cleaned_titanic_data.csv', index=False)
print("\nCleaned dataset exported as 'cleaned_titanic_data.csv'.")

          Metric Status BEFORE Cleaning AFTER Cleaning
0       Total Row Count             891            775
1  Total Missing Values             869              0
2  Total Duplicate Rows             107              6
3    Deck Column Status         Present        Dropped
4  Fare Outliers Capped              No      Yes (102)

Cleaned dataset exported as 'cleaned_titanic_data.csv'.

### Final Cleaned Dataset Preview
The code below displays the final state of the dataset that was exported to the CSV file.

In [21]:
# Display the final cleaned DataFrame
display(df.head())
print(f"Final Dataset Shape: {df.shape}")

# Confirming the file path in the current environment
import os
file_path = '/content/cleaned_titanic_data.csv'
if os.path.exists(file_path):
    print(f"Success: Dataset is saved at {file_path}")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

Final Dataset Shape: (775, 14)
Success: Dataset is saved at /content/cleaned_titanic_data.csv

### Task Summary & Professional Recommendations

**Conclusion:**
The data pipeline successfully transformed the raw Titanic dataset into a clean, analysis-ready version.

**Key Recommendations:**
1. **Validation:** Implement upstream validation to reduce initial missingness.
2. **Monitoring:** Use dynamic capping (like IQR) for financial metrics to handle extreme variance.
3. **Versioning:** Always maintain the link between raw and cleaned CSV assets for auditing purposes.

## Data Cleaning & Audit Report

### 1. Final Results Summary:
After executing the data processing pipeline, the following results were achieved:
*   **Data Volume:** The dataset was reduced from 891 rows to 775 rows after deduplication.
*   **Missing Values:** All missing values were resolved (0 Missing Values) across the entire table.
*   **Outliers:** 102 extreme values in the 'Fare' column were successfully addressed.

### 2. Cleaning Methodology & Technical Reasoning:

#### A. Missing Data Handling:
*   **Age:** The **Median** was used instead of the mean because the age distribution is skewed. The median is more robust against outliers and provides a more central representation for this specific dataset.
*   **Embarked:** The **Mode** (most frequent value) was used as this is a categorical column where mathematical averages are not applicable.
*   **Deck Column:** A decision was made to **Drop** this column entirely because missingness exceeded 70%. Imputing such a high volume of data would introduce significant bias and mislead statistical models.

#### B. Duplicate Removal:
*   116 duplicate rows were removed. This step is critical to prevent 'data leakage' and ensure that identical records do not receive disproportionate weight during analysis or machine learning training.

#### C. Outlier Management:
*   **IQR Method:** The Interquartile Range method was used to establish statistical boundaries.
*   **Capping Strategy:** Instead of deleting outlier rows, we capped values at the upper bound (73.42). This preserves the data volume while mitigating the influence of extreme values that distort statistical distributions.

### 3. Professional Recommendations:
*   The dataset is now structured for Exploratory Data Analysis (EDA) or predictive modeling.
*   It is recommended to maintain the `df_original` reference used in this notebook for future audit trails and quality verification.